export const ANIME_CATALOG = [
  {
    title: "Ping Pong the Animation",
    title_jp: "ピンポン THE ANIMATION",
    year: 2014,
    episodes: 11,
    genre: "Sports, Drama",
    genres: ["sports", "drama", "coming-of-age"],
    themes: ["talent", "envy", "friendship", "purpose"],
    pacing: "brisk",
    darkness: 2,
    psychological: 4,
    action: 3,
    comfort: 2,
    franchise: "ping-pong"
  },
  {
    title: "Odd Taxi",
    title_jp: "オッドタクシー",
    year: 2021,
    episodes: 13,
    genre: "Mystery, Drama",
    genres: ["mystery", "drama", "crime"],
    themes: ["loneliness", "routine", "secrets", "consequence"],
    pacing: "steady",
    darkness: 3,
    psychological: 5,
    action: 1,
    comfort: 1,
    franchise: "odd-taxi"
  },
  {
    title: "Run with the Wind",
    title_jp: "風が強く吹いている",
    year: 2018,
    episodes: 23,
    genre: "Sports, Drama",
    genres: ["sports", "drama", "slice-of-life"],
    themes: ["discipline", "friendship", "failure", "recovery"],
    pacing: "steady",
    darkness: 1,
    psychological: 3,
    action: 2,
    comfort: 4,
    franchise: "run-with-the-wind"
  },
  {
    title: "Showa Genroku Rakugo Shinju",
    title_jp: "昭和元禄落語心中",
    year: 2016,
    episodes: 13,
    genre: "Drama, Historical",
    genres: ["drama", "historical", "performing-arts"],
    themes: ["regret", "art", "aging", "devotion"],
    pacing: "slow",
    darkness: 3,
    psychological: 5,
    action: 0,
    comfort: 1,
    franchise: "rakugo-shinju"
  },
  {
    title: "A Place Further Than the Universe",
    title_jp: "宇宙よりも遠い場所",
    year: 2018,
    episodes: 13,
    genre: "Adventure, Drama",
    genres: ["adventure", "drama", "slice-of-life"],
    themes: ["grief", "friendship", "leaving-home", "courage"],
    pacing: "steady",
    darkness: 2,
    psychological: 3,
    action: 1,
    comfort: 4,
    franchise: "yorimoi"
  },
  {
    title: "Barakamon",
    title_jp: "ばらかもん",
    year: 2014,
    episodes: 12,
    genre: "Slice of Life, Comedy",
    genres: ["slice-of-life", "comedy", "healing"],
    themes: ["burnout", "community", "art", "starting-over"],
    pacing: "easy",
    darkness: 0,
    psychological: 2,
    action: 0,
    comfort: 5,
    franchise: "barakamon"
  },
  {
    title: "Mushishi",
    title_jp: "蟲師",
    year: 2005,
    episodes: 26,
    genre: "Supernatural, Mystery",
    genres: ["supernatural", "mystery", "slice-of-life"],
    themes: ["nature", "loss", "acceptance", "quiet"],
    pacing: "slow",
    darkness: 2,
    psychological: 4,
    action: 0,
    comfort: 4,
    franchise: "mushishi"
  },
  {
    title: "Serial Experiments Lain",
    title_jp: "serial experiments lain",
    year: 1998,
    episodes: 13,
    genre: "Psychological, Sci-Fi",
    genres: ["psychological", "sci-fi", "mystery"],
    themes: ["identity", "isolation", "technology", "paranoia"],
    pacing: "slow",
    darkness: 4,
    psychological: 5,
    action: 0,
    comfort: 0,
    franchise: "lain"
  },
  {
    title: "Haibane Renmei",
    title_jp: "灰羽連盟",
    year: 2002,
    episodes: 13,
    genre: "Drama, Fantasy",
    genres: ["drama", "fantasy", "slice-of-life"],
    themes: ["guilt", "forgiveness", "community", "quiet"],
    pacing: "slow",
    darkness: 3,
    psychological: 4,
    action: 0,
    comfort: 3,
    franchise: "haibane-renmei"
  },
  {
    title: "Texhnolyze",
    title_jp: "TEXHNOLYZE",
    year: 2003,
    episodes: 22,
    genre: "Psychological, Sci-Fi",
    genres: ["psychological", "sci-fi", "drama"],
    themes: ["decay", "violence", "fate", "nihilism"],
    pacing: "slow",
    darkness: 5,
    psychological: 5,
    action: 2,
    comfort: 0,
    franchise: "texhnolyze"
  },
  {
    title: "Monster",
    title_jp: "MONSTER",
    year: 2004,
    episodes: 74,
    genre: "Thriller, Drama",
    genres: ["thriller", "drama", "mystery"],
    themes: ["morality", "guilt", "evil", "obsession"],
    pacing: "slow",
    darkness: 5,
    psychological: 5,
    action: 1,
    comfort: 0,
    franchise: "monster"
  },
  {
    title: "Paranoia Agent",
    title_jp: "妄想代理人",
    year: 2004,
    episodes: 13,
    genre: "Psychological, Mystery",
    genres: ["psychological", "mystery", "thriller"],
    themes: ["stress", "denial", "society", "fear"],
    pacing: "brisk",
    darkness: 4,
    psychological: 5,
    action: 1,
    comfort: 0,
    franchise: "paranoia-agent"
  },
  {
    title: "Kaiba",
    title_jp: "カイバ",
    year: 2008,
    episodes: 12,
    genre: "Sci-Fi, Drama",
    genres: ["sci-fi", "drama", "adventure"],
    themes: ["memory", "class", "love", "identity"],
    pacing: "steady",
    darkness: 3,
    psychological: 4,
    action: 1,
    comfort: 1,
    franchise: "kaiba"
  },
  {
    title: "Dennou Coil",
    title_jp: "電脳コイル",
    year: 2007,
    episodes: 26,
    genre: "Sci-Fi, Mystery",
    genres: ["sci-fi", "mystery", "adventure"],
    themes: ["childhood", "technology", "grief", "curiosity"],
    pacing: "steady",
    darkness: 2,
    psychological: 3,
    action: 2,
    comfort: 3,
    franchise: "dennou-coil"
  },
  {
    title: "Sonny Boy",
    title_jp: "Sonny Boy",
    year: 2021,
    episodes: 12,
    genre: "Sci-Fi, Drama",
    genres: ["sci-fi", "drama", "surreal"],
    themes: ["alienation", "youth", "freedom", "failure"],
    pacing: "slow",
    darkness: 3,
    psychological: 5,
    action: 1,
    comfort: 1,
    franchise: "sonny-boy"
  },
  {
    title: "Kino's Journey",
    title_jp: "キノの旅",
    year: 2003,
    episodes: 13,
    genre: "Adventure, Philosophical",
    genres: ["adventure", "drama", "philosophical"],
    themes: ["travel", "morality", "distance", "choice"],
    pacing: "slow",
    darkness: 3,
    psychological: 4,
    action: 1,
    comfort: 2,
    franchise: "kinos-journey"
  },
  {
    title: "Girls' Last Tour",
    title_jp: "少女終末旅行",
    year: 2017,
    episodes: 12,
    genre: "Slice of Life, Sci-Fi",
    genres: ["slice-of-life", "sci-fi", "adventure"],
    themes: ["endings", "companionship", "quiet", "survival"],
    pacing: "slow",
    darkness: 3,
    psychological: 3,
    action: 0,
    comfort: 4,
    franchise: "girls-last-tour"
  },
  {
    title: "Land of the Lustrous",
    title_jp: "宝石の国",
    year: 2017,
    episodes: 12,
    genre: "Fantasy, Drama",
    genres: ["fantasy", "drama", "action"],
    themes: ["identity", "change", "body", "purpose"],
    pacing: "steady",
    darkness: 3,
    psychological: 4,
    action: 3,
    comfort: 1,
    franchise: "land-of-the-lustrous"
  },
  {
    title: "March Comes in Like a Lion",
    title_jp: "3月のライオン",
    year: 2016,
    episodes: 22,
    genre: "Drama, Slice of Life",
    genres: ["drama", "slice-of-life", "coming-of-age"],
    themes: ["depression", "family", "recovery", "solitude"],
    pacing: "slow",
    darkness: 3,
    psychological: 5,
    action: 0,
    comfort: 4,
    franchise: "march-lion"
  },
  {
    title: "Shirobako",
    title_jp: "SHIROBAKO",
    year: 2014,
    episodes: 24,
    genre: "Workplace, Comedy",
    genres: ["workplace", "comedy", "drama"],
    themes: ["work", "ambition", "burnout", "friendship"],
    pacing: "brisk",
    darkness: 1,
    psychological: 2,
    action: 0,
    comfort: 4,
    franchise: "shirobako"
  },
  {
    title: "Hyouka",
    title_jp: "氷菓",
    year: 2012,
    episodes: 22,
    genre: "Mystery, Slice of Life",
    genres: ["mystery", "slice-of-life", "school"],
    themes: ["curiosity", "restraint", "memory", "youth"],
    pacing: "slow",
    darkness: 1,
    psychological: 3,
    action: 0,
    comfort: 4,
    franchise: "hyouka"
  },
  {
    title: "The Great Passage",
    title_jp: "舟を編む",
    year: 2016,
    episodes: 11,
    genre: "Drama, Slice of Life",
    genres: ["drama", "slice-of-life", "workplace"],
    themes: ["language", "patience", "work", "devotion"],
    pacing: "slow",
    darkness: 0,
    psychological: 3,
    action: 0,
    comfort: 5,
    franchise: "great-passage"
  },
  {
    title: "Wave, Listen to Me!",
    title_jp: "波よ聞いてくれ",
    year: 2020,
    episodes: 12,
    genre: "Comedy, Drama",
    genres: ["comedy", "drama", "workplace"],
    themes: ["reinvention", "anger", "voice", "adult-life"],
    pacing: "brisk",
    darkness: 1,
    psychological: 2,
    action: 0,
    comfort: 3,
    franchise: "wave-listen"
  },
  {
    title: "Keep Your Hands Off Eizouken!",
    title_jp: "映像研には手を出すな!",
    year: 2020,
    episodes: 12,
    genre: "Adventure, Comedy",
    genres: ["adventure", "comedy", "school"],
    themes: ["creativity", "friendship", "obsession", "making-things"],
    pacing: "brisk",
    darkness: 0,
    psychological: 2,
    action: 1,
    comfort: 4,
    franchise: "eizouken"
  },
  {
    title: "Planetes",
    title_jp: "プラネテス",
    year: 2003,
    episodes: 26,
    genre: "Sci-Fi, Drama",
    genres: ["sci-fi", "drama", "workplace"],
    themes: ["work", "ambition", "space", "responsibility"],
    pacing: "steady",
    darkness: 2,
    psychological: 3,
    action: 1,
    comfort: 3,
    franchise: "planetes"
  },
  {
    title: "Ergo Proxy",
    title_jp: "エルゴプラクシー",
    year: 2006,
    episodes: 23,
    genre: "Sci-Fi, Psychological",
    genres: ["sci-fi", "psychological", "mystery"],
    themes: ["identity", "control", "memory", "collapse"],
    pacing: "slow",
    darkness: 4,
    psychological: 5,
    action: 2,
    comfort: 0,
    franchise: "ergo-proxy"
  },
  {
    title: "From the New World",
    title_jp: "新世界より",
    year: 2012,
    episodes: 25,
    genre: "Sci-Fi, Mystery",
    genres: ["sci-fi", "mystery", "drama"],
    themes: ["society", "fear", "memory", "power"],
    pacing: "slow",
    darkness: 5,
    psychological: 5,
    action: 2,
    comfort: 0,
    franchise: "from-the-new-world"
  },
  {
    title: "Moribito: Guardian of the Spirit",
    title_jp: "精霊の守り人",
    year: 2007,
    episodes: 26,
    genre: "Fantasy, Adventure",
    genres: ["fantasy", "adventure", "drama"],
    themes: ["duty", "protection", "maturity", "travel"],
    pacing: "steady",
    darkness: 2,
    psychological: 3,
    action: 3,
    comfort: 3,
    franchise: "moribito"
  },
  {
    title: "Seirei no Moribito",
    title_jp: "精霊の守り人",
    year: 2007,
    episodes: 26,
    genre: "Fantasy, Adventure",
    genres: ["fantasy", "adventure", "drama"],
    themes: ["duty", "protection", "maturity", "travel"],
    pacing: "steady",
    darkness: 2,
    psychological: 3,
    action: 3,
    comfort: 3,
    franchise: "moribito"
  },
  {
    title: "Baccano!",
    title_jp: "バッカーノ!",
    year: 2007,
    episodes: 13,
    genre: "Action, Mystery",
    genres: ["action", "mystery", "crime"],
    themes: ["chaos", "violence", "fate", "ensemble"],
    pacing: "fast",
    darkness: 3,
    psychological: 2,
    action: 4,
    comfort: 1,
    franchise: "baccano"
  },
  {
    title: "Samurai Champloo",
    title_jp: "サムライチャンプルー",
    year: 2004,
    episodes: 26,
    genre: "Action, Adventure",
    genres: ["action", "adventure", "comedy"],
    themes: ["travel", "style", "freedom", "companionship"],
    pacing: "brisk",
    darkness: 2,
    psychological: 2,
    action: 5,
    comfort: 3,
    franchise: "samurai-champloo"
  },
  {
    title: "Megalo Box",
    title_jp: "メガロボクス",
    year: 2018,
    episodes: 13,
    genre: "Sports, Action",
    genres: ["sports", "action", "drama"],
    themes: ["pride", "class", "risk", "reinvention"],
    pacing: "brisk",
    darkness: 2,
    psychological: 3,
    action: 4,
    comfort: 1,
    franchise: "megalo-box"
  },
  {
    title: "86 Eighty-Six",
    title_jp: "86―エイティシックス―",
    year: 2021,
    episodes: 11,
    genre: "Action, Drama",
    genres: ["action", "drama", "sci-fi"],
    themes: ["war", "grief", "prejudice", "survival"],
    pacing: "steady",
    darkness: 4,
    psychological: 3,
    action: 4,
    comfort: 0,
    franchise: "86"
  },
  {
    title: "Mob Psycho 100",
    title_jp: "モブサイコ100",
    year: 2016,
    episodes: 12,
    genre: "Action, Comedy",
    genres: ["action", "comedy", "supernatural"],
    themes: ["self-control", "kindness", "growth", "power"],
    pacing: "fast",
    darkness: 1,
    psychological: 3,
    action: 5,
    comfort: 4,
    franchise: "mob-psycho"
  },
  {
    title: "Cyberpunk: Edgerunners",
    title_jp: "サイバーパンク エッジランナーズ",
    year: 2022,
    episodes: 10,
    genre: "Action, Sci-Fi",
    genres: ["action", "sci-fi", "drama"],
    themes: ["ambition", "loss", "class", "speed"],
    pacing: "fast",
    darkness: 4,
    psychological: 3,
    action: 5,
    comfort: 0,
    franchise: "cyberpunk-edgerunners"
  },
  {
    title: "Akudama Drive",
    title_jp: "アクダマドライブ",
    year: 2020,
    episodes: 12,
    genre: "Action, Sci-Fi",
    genres: ["action", "sci-fi", "crime"],
    themes: ["identity", "spectacle", "violence", "escape"],
    pacing: "fast",
    darkness: 4,
    psychological: 2,
    action: 5,
    comfort: 0,
    franchise: "akudama-drive"
  },
  {
    title: "Vivy: Fluorite Eye's Song",
    title_jp: "Vivy -Fluorite Eye's Song-",
    year: 2021,
    episodes: 13,
    genre: "Action, Sci-Fi",
    genres: ["action", "sci-fi", "drama"],
    themes: ["purpose", "memory", "music", "sacrifice"],
    pacing: "brisk",
    darkness: 3,
    psychological: 3,
    action: 4,
    comfort: 1,
    franchise: "vivy"
  },
  {
    title: "Deca-Dence",
    title_jp: "デカダンス",
    year: 2020,
    episodes: 12,
    genre: "Action, Sci-Fi",
    genres: ["action", "sci-fi", "adventure"],
    themes: ["systems", "freedom", "rebellion", "identity"],
    pacing: "brisk",
    darkness: 2,
    psychological: 2,
    action: 4,
    comfort: 2,
    franchise: "deca-dence"
  },
  {
    title: "ACCA: 13-Territory Inspection Dept.",
    title_jp: "ACCA13区監察課",
    year: 2017,
    episodes: 12,
    genre: "Political, Drama",
    genres: ["political", "drama", "mystery"],
    themes: ["trust", "routine", "power", "restraint"],
    pacing: "slow",
    darkness: 1,
    psychological: 3,
    action: 0,
    comfort: 3,
    franchise: "acca"
  },
  {
    title: "The Eccentric Family",
    title_jp: "有頂天家族",
    year: 2013,
    episodes: 13,
    genre: "Drama, Fantasy",
    genres: ["drama", "fantasy", "slice-of-life"],
    themes: ["family", "grief", "tradition", "mischief"],
    pacing: "steady",
    darkness: 2,
    psychological: 3,
    action: 1,
    comfort: 4,
    franchise: "eccentric-family"
  },
  {
    title: "Natsume's Book of Friends",
    title_jp: "夏目友人帳",
    year: 2008,
    episodes: 13,
    genre: "Supernatural, Slice of Life",
    genres: ["supernatural", "slice-of-life", "healing"],
    themes: ["loneliness", "kindness", "memory", "belonging"],
    pacing: "slow",
    darkness: 1,
    psychological: 3,
    action: 0,
    comfort: 5,
    franchise: "natsume"
  },
  {
    title: "Aria the Animation",
    title_jp: "ARIA The ANIMATION",
    year: 2005,
    episodes: 13,
    genre: "Slice of Life, Sci-Fi",
    genres: ["slice-of-life", "sci-fi", "healing"],
    themes: ["quiet", "work", "wonder", "friendship"],
    pacing: "slow",
    darkness: 0,
    psychological: 2,
    action: 0,
    comfort: 5,
    franchise: "aria"
  },
  {
    title: "Yuru Camp",
    title_jp: "ゆるキャン△",
    year: 2018,
    episodes: 12,
    genre: "Slice of Life, Comedy",
    genres: ["slice-of-life", "comedy", "healing"],
    themes: ["rest", "friendship", "routine", "food"],
    pacing: "easy",
    darkness: 0,
    psychological: 1,
    action: 0,
    comfort: 5,
    franchise: "yuru-camp"
  },
  {
    title: "Non Non Biyori",
    title_jp: "のんのんびより",
    year: 2013,
    episodes: 12,
    genre: "Slice of Life, Comedy",
    genres: ["slice-of-life", "comedy", "healing"],
    themes: ["childhood", "rural-life", "quiet", "routine"],
    pacing: "easy",
    darkness: 0,
    psychological: 1,
    action: 0,
    comfort: 5,
    franchise: "non-non-biyori"
  },
  {
    title: "Silver Spoon",
    title_jp: "銀の匙",
    year: 2013,
    episodes: 11,
    genre: "Comedy, Slice of Life",
    genres: ["comedy", "slice-of-life", "school"],
    themes: ["work", "food", "growth", "practical-life"],
    pacing: "steady",
    darkness: 1,
    psychological: 2,
    action: 0,
    comfort: 4,
    franchise: "silver-spoon"
  },
  {
    title: "Princess Jellyfish",
    title_jp: "海月姫",
    year: 2010,
    episodes: 11,
    genre: "Comedy, Drama",
    genres: ["comedy", "drama", "romance"],
    themes: ["self-image", "community", "change", "awkwardness"],
    pacing: "brisk",
    darkness: 1,
    psychological: 2,
    action: 0,
    comfort: 4,
    franchise: "princess-jellyfish"
  },
  {
    title: "Kids on the Slope",
    title_jp: "坂道のアポロン",
    year: 2012,
    episodes: 12,
    genre: "Drama, Music",
    genres: ["drama", "music", "romance"],
    themes: ["friendship", "youth", "jealousy", "music"],
    pacing: "steady",
    darkness: 2,
    psychological: 3,
    action: 0,
    comfort: 3,
    franchise: "kids-on-the-slope"
  },
  {
    title: "Nana",
    title_jp: "NANA",
    year: 2006,
    episodes: 47,
    genre: "Drama, Music",
    genres: ["drama", "music", "romance"],
    themes: ["love", "ambition", "friendship", "adult-life"],
    pacing: "steady",
    darkness: 3,
    psychological: 4,
    action: 0,
    comfort: 1,
    franchise: "nana"
  },
  {
    title: "Honey and Clover",
    title_jp: "ハチミツとクローバー",
    year: 2005,
    episodes: 24,
    genre: "Drama, Romance",
    genres: ["drama", "romance", "slice-of-life"],
    themes: ["unrequited-love", "youth", "art", "uncertainty"],
    pacing: "slow",
    darkness: 2,
    psychological: 4,
    action: 0,
    comfort: 2,
    franchise: "honey-and-clover"
  },
  {
    title: "Paradise Kiss",
    title_jp: "Paradise Kiss",
    year: 2005,
    episodes: 12,
    genre: "Drama, Romance",
    genres: ["drama", "romance", "fashion"],
    themes: ["identity", "ambition", "romance", "leaving-home"],
    pacing: "steady",
    darkness: 2,
    psychological: 3,
    action: 0,
    comfort: 1,
    franchise: "paradise-kiss"
  },
  {
    title: "Bloom Into You",
    title_jp: "やがて君になる",
    year: 2018,
    episodes: 13,
    genre: "Romance, Drama",
    genres: ["romance", "drama", "school"],
    themes: ["identity", "love", "performance", "restraint"],
    pacing: "slow",
    darkness: 1,
    psychological: 4,
    action: 0,
    comfort: 2,
    franchise: "bloom-into-you"
  },
  {
    title: "Tsuki ga Kirei",
    title_jp: "月がきれい",
    year: 2017,
    episodes: 12,
    genre: "Romance, Slice of Life",
    genres: ["romance", "slice-of-life", "school"],
    themes: ["first-love", "quiet", "distance", "growing-up"],
    pacing: "slow",
    darkness: 0,
    psychological: 2,
    action: 0,
    comfort: 4,
    franchise: "tsuki-ga-kirei"
  },
  {
    title: "After the Rain",
    title_jp: "恋は雨上がりのように",
    year: 2018,
    episodes: 12,
    genre: "Drama, Romance",
    genres: ["drama", "romance", "slice-of-life"],
    themes: ["longing", "injury", "restraint", "moving-on"],
    pacing: "slow",
    darkness: 1,
    psychological: 3,
    action: 0,
    comfort: 3,
    franchise: "after-the-rain"
  },
  {
    title: "Skip and Loafer",
    title_jp: "スキップとローファー",
    year: 2023,
    episodes: 12,
    genre: "Slice of Life, Comedy",
    genres: ["slice-of-life", "comedy", "school"],
    themes: ["kindness", "friendship", "awkwardness", "growth"],
    pacing: "easy",
    darkness: 0,
    psychological: 2,
    action: 0,
    comfort: 5,
    franchise: "skip-and-loafer"
  },
  {
    title: "Insomniacs After School",
    title_jp: "君は放課後インソムニア",
    year: 2023,
    episodes: 13,
    genre: "Romance, Slice of Life",
    genres: ["romance", "slice-of-life", "school"],
    themes: ["sleep", "quiet", "intimacy", "youth"],
    pacing: "slow",
    darkness: 1,
    psychological: 2,
    action: 0,
    comfort: 4,
    franchise: "insomniacs-after-school"
  },
  {
    title: "Heike Monogatari",
    title_jp: "平家物語",
    year: 2021,
    episodes: 11,
    genre: "Historical, Drama",
    genres: ["historical", "drama"],
    themes: ["loss", "family", "war", "impermanence"],
    pacing: "steady",
    darkness: 4,
    psychological: 4,
    action: 2,
    comfort: 0,
    franchise: "heike-monogatari"
  },
  {
    title: "The Case Study of Vanitas",
    title_jp: "ヴァニタスの手記",
    year: 2021,
    episodes: 12,
    genre: "Fantasy, Mystery",
    genres: ["fantasy", "mystery", "action"],
    themes: ["curse", "identity", "trauma", "style"],
    pacing: "brisk",
    darkness: 3,
    psychological: 3,
    action: 3,
    comfort: 1,
    franchise: "vanitas"
  },
  {
    title: "Katanagatari",
    title_jp: "刀語",
    year: 2010,
    episodes: 12,
    genre: "Action, Adventure",
    genres: ["action", "adventure", "historical"],
    themes: ["duty", "love", "violence", "fate"],
    pacing: "steady",
    darkness: 3,
    psychological: 3,
    action: 4,
    comfort: 1,
    franchise: "katanagatari"
  },
  {
    title: "Dororo",
    title_jp: "どろろ",
    year: 2019,
    episodes: 24,
    genre: "Action, Historical",
    genres: ["action", "historical", "drama"],
    themes: ["body", "revenge", "family", "war"],
    pacing: "steady",
    darkness: 4,
    psychological: 3,
    action: 4,
    comfort: 0,
    franchise: "dororo"
  },
  {
    title: "Golden Kamuy",
    title_jp: "ゴールデンカムイ",
    year: 2018,
    episodes: 12,
    genre: "Adventure, Historical",
    genres: ["adventure", "historical", "comedy"],
    themes: ["survival", "food", "greed", "history"],
    pacing: "brisk",
    darkness: 3,
    psychological: 2,
    action: 4,
    comfort: 2,
    franchise: "golden-kamuy"
  },
  {
    title: "Made in Abyss",
    title_jp: "メイドインアビス",
    year: 2017,
    episodes: 13,
    genre: "Adventure, Fantasy",
    genres: ["adventure", "fantasy", "drama"],
    themes: ["curiosity", "danger", "body-horror", "descent"],
    pacing: "steady",
    darkness: 5,
    psychological: 4,
    action: 3,
    comfort: 0,
    franchise: "made-in-abyss"
  },
  {
    title: "Dorohedoro",
    title_jp: "ドロヘドロ",
    year: 2020,
    episodes: 12,
    genre: "Action, Dark Comedy",
    genres: ["action", "dark-comedy", "fantasy"],
    themes: ["violence", "identity", "friendship", "absurdity"],
    pacing: "fast",
    darkness: 4,
    psychological: 2,
    action: 5,
    comfort: 1,
    franchise: "dorohedoro"
  },
  {
    title: "Golden Time",
    title_jp: "ゴールデンタイム",
    year: 2013,
    episodes: 24,
    genre: "Romance, Drama",
    genres: ["romance", "drama", "comedy"],
    themes: ["memory", "identity", "love", "college"],
    pacing: "steady",
    darkness: 2,
    psychological: 3,
    action: 0,
    comfort: 2,
    franchise: "golden-time"
  },
  {
    title: "Terror in Resonance",
    title_jp: "残響のテロル",
    year: 2014,
    episodes: 11,
    genre: "Thriller, Drama",
    genres: ["thriller", "drama", "mystery"],
    themes: ["trauma", "isolation", "revenge", "memory"],
    pacing: "brisk",
    darkness: 4,
    psychological: 4,
    action: 3,
    comfort: 0,
    franchise: "terror-in-resonance"
  },
  {
    title: "ID: INVADED",
    title_jp: "イド：インヴェイデッド",
    year: 2020,
    episodes: 13,
    genre: "Mystery, Sci-Fi",
    genres: ["mystery", "sci-fi", "thriller"],
    themes: ["grief", "identity", "crime", "mind"],
    pacing: "brisk",
    darkness: 4,
    psychological: 5,
    action: 2,
    comfort: 0,
    franchise: "id-invaded"
  },
  {
    title: "Boogiepop and Others",
    title_jp: "ブギーポップは笑わない",
    year: 2019,
    episodes: 18,
    genre: "Mystery, Supernatural",
    genres: ["mystery", "supernatural", "psychological"],
    themes: ["identity", "fear", "youth", "urban-legend"],
    pacing: "slow",
    darkness: 4,
    psychological: 5,
    action: 1,
    comfort: 0,
    franchise: "boogiepop"
  },
  {
    title: "Mononoke",
    title_jp: "モノノ怪",
    year: 2007,
    episodes: 12,
    genre: "Horror, Mystery",
    genres: ["horror", "mystery", "supernatural"],
    themes: ["truth", "grief", "violence", "ritual"],
    pacing: "slow",
    darkness: 4,
    psychological: 5,
    action: 1,
    comfort: 0,
    franchise: "mononoke"
  },
  {
    title: "The Big O",
    title_jp: "THE ビッグオー",
    year: 1999,
    episodes: 26,
    genre: "Mecha, Mystery",
    genres: ["mecha", "mystery", "action"],
    themes: ["memory", "city", "identity", "style"],
    pacing: "steady",
    darkness: 2,
    psychological: 3,
    action: 4,
    comfort: 2,
    franchise: "big-o"
  },
  {
    title: "Gankutsuou: The Count of Monte Cristo",
    title_jp: "巌窟王",
    year: 2004,
    episodes: 24,
    genre: "Drama, Sci-Fi",
    genres: ["drama", "sci-fi", "thriller"],
    themes: ["revenge", "class", "betrayal", "obsession"],
    pacing: "steady",
    darkness: 4,
    psychological: 4,
    action: 2,
    comfort: 0,
    franchise: "gankutsuou"
  },
  {
    title: "Wolf's Rain",
    title_jp: "WOLF'S RAIN",
    year: 2003,
    episodes: 26,
    genre: "Adventure, Drama",
    genres: ["adventure", "drama", "fantasy"],
    themes: ["survival", "loss", "faith", "belonging"],
    pacing: "slow",
    darkness: 4,
    psychological: 3,
    action: 2,
    comfort: 0,
    franchise: "wolfs-rain"
  },
  {
    title: "Beastars",
    title_jp: "BEASTARS",
    year: 2019,
    episodes: 12,
    genre: "Drama, Psychological",
    genres: ["drama", "psychological", "mystery"],
    themes: ["desire", "identity", "society", "violence"],
    pacing: "steady",
    darkness: 3,
    psychological: 4,
    action: 2,
    comfort: 0,
    franchise: "beastars"
  }
];
